### ISSUE TITLE
Question on permutation size

### ISSUE THREAD

**Issue by danich1** [dhimmel/learn#4]
```python
# Calculate the number of perms
n_perm = treatment_df.compound_id.nunique() * treatment_df.disease_id.nunique()
n_perm = int(n_perm * 25)
n_perm
```

I wanted to know why the number of permutations for the Drug-Gene network in your `prior/1-prior.ipynb` notebook is 744975 and not 29799. Is it that the possible number of permutations is too low?

**Comment by dhimmel** [comment]
From https://think-lab.github.io/d/201/#2:

> Since we struggled to solve this problem analytically, we applied a brute-force permutation approach. Specifically, we took our empiric bipartite treatment network (PharmacotherapyDB) with 755 treatments and derived 744,975 permuted networks.

> We applied the XSwap method of permutation [1, 2, 3] and found 2,265 (755 × 3) attempted swaps provided sufficient randomization [4] ([notebook](https://github.com/dhimmel/learn/blob/0aae784e83cfaa00d1269f17a3bd3a6c6fdc3a0a/prior/1-prior.ipynb)). After every permutation, we recorded the percent of possible edges that were present for each degree pair. The final result is the prior probability that each degree pair exists ([table](https://github.com/dhimmel/learn/blob/0aae784e83cfaa00d1269f17a3bd3a6c6fdc3a0a/prior/data/degree-prior.tsv)).

You want to sample a sufficient number of permutations such that `prior_perm_stderr` is low relative to `prior_perm`. In other words, you need enough permutations so that the `prior_perm` estimates are accurate. Judge this from the degree combinations that are more rare, as their uncertainty takes longer to weed out.
